### PR TITLE
Merge pull request #3 from mdht/develop

### PR DESCRIPTION
**Pull request by patins1**
makes analysis constraints from referenced packages come through in publication

### CODE REVIEW

**Comment by vadimnehta** [comment]
What is the PR trying to do?

**Comment by patins1** [comment]
Hi Vadim,

The PR fixes this ticket:

|
|
|

It adds some missing analysis constraints into the PDF,

Cheeres

**Comment by vadimnehta** [comment]
Oh - description says "update my mdht fork".

Would be better to say that it makes analysis constraints from referenced packages come through in publication.

**Comment by patins1** [comment]
Closing pull requeset as Vadim suggested a different solution

**Pull request closed without merging**
